# Generated by Django 6.0.6 on 2026-07-07 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('front', models.TextField(max_length=2048)),
                ('back', models.TextField(max_length=2048)),
                ('score', models.IntegerField()),
                ('card_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cardlist')),
            ],
        ),
    ]
