# Generated by Django 6.0.6 on 2026-07-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cardlist_deck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='card_list',
            new_name='deck_id',
        ),
    ]
