# Generated by Django 6.0.6 on 2026-07-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_card_list_card_deck_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['deck', 'index']},
        ),
        migrations.RenameField(
            model_name='card',
            old_name='deck_id',
            new_name='deck',
        ),
        migrations.RemoveField(
            model_name='card',
            name='id',
        ),
        migrations.AddField(
            model_name='card',
            name='pk',
            field=models.CompositePrimaryKey('deck_id', 'index', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deck',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('deck', 'index'), name='unique_deck_index'),
        ),
    ]
